# Generated by Django 3.2.12 on 2022-11-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On the Way'), ('Delivered successfully', 'Delivered successfully'), ('Cancel order', 'Cancel order')], default='Pending', max_length=50),
        ),
    ]
